# How to use :
# docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '2'
services:

  nexus_oss_2:
    hostname: NEXUS_OSS_2
    container_name: NEXUS_OSS_2
    build: 
      context: ./nexus2
      dockerfile: ./Dockerfile
    environment: 
      MAX_HEAP: 768m
      MIN_HEAP: 256m
    volumes:
      - ./nexus2/sonatype-work:/sonatype-work
    ports:
      - 8082:8081
    networks: 
      vpn:
        ipv4_address: 172.168.50.2
    restart: unless-stopped

  nexus_oss_3:
    hostname: NEXUS_OSS_3
    container_name: NEXUS_OSS_3
    image: sonatype/nexus3:3.34.0
    environment: 
      MAX_HEAP: 768m
      MIN_HEAP: 256m
    volumes:
      - ./nexus3/sonatype-work:/nexus-data
    ports:
      - 8083:8081
    networks: 
      vpn:
        ipv4_address: 172.168.50.3
    restart: unless-stopped


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.50.0/24
          gateway: 172.168.50.1

